name: EternalCrates
main: xyz.oribuin.eternalcrates.EternalCrates
version: '1.0.5'
api-version: '1.13'
author: Oribuin
description: A new crate plugin focused on functional, performance and animation.
softdepend:
  - PlaceholderAPI
  - eco
  - ItemBridge
  - ItemEdit
  - ItemsAdder
  - CustomItems
  - MMOItems
  - Oraxen
  - Slimefun
  - UberItems