name: EternalCrates
main: xyz.oribuin.eternalcrates.EternalCrates
version: '@version@'
api-version: '1.13'
author: Oribuin
description: A new crate plugin focused on functionality, performance and animation.
softdepend:
  - PlaceholderAPI
  - eco
  - ItemBridge
  - ItemEdit
  - ItemsAdder
  - CustomItems
  - MMOItems
  - Oraxen
  - Slimefun
  - UberItems